### ISSUE TITLE
Update Frequency Metadata Portal with Parity's new design

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/metadata-portal#41]
The upstream metadata portal looks so much better and is easier to use.

We should update to it.

## Expected
- [x] Rebase
- [x] Re-fix all the issues with Frequency logos and such
- [ ] Ship it

**Comment by rlaferla** [comment]
As per discussion with @wilwade, the updated version will not include a the network/portal selector.  It will only list Frequency and Frequency Rococo networks.
