### ISSUE TITLE
Fix Deploy Workflow

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/metadata-portal#49]
Currently failing: https://github.com/LibertyDSNP/metadata-portal/actions/runs/5144442985

**Comment by rlaferla** [comment]
[2023-06-02T10:27:43Z ERROR] error decoding response body: missing field `version` at line 21 column 5

**Comment by rlaferla** [comment]
The verifier public key is incorrect.

**Comment by wilwade** [comment]
@rlaferla Did we overwrite the key with the upstream upgrade?

**Comment by rlaferla** [comment]
@wilwade No.

**Comment by rlaferla** [comment]
The issue is that the `data.json` from the old Metadata Portal is still live and the deployment check is comparing it against a freshly generated `data.json` (which has a slightly different format.)

**Comment by rlaferla** [comment]
New portal successfully deployed.  Need to refresh the data and add some additional documentation.

**Comment by rlaferla** [comment]
<img width="1679" alt="image" src="https://github.com/LibertyDSNP/metadata-portal/assets/1135694/8c35e51f-253e-47df-9de9-654772e0bc10">
